# Functional-equivalence verification

This notebook verifies the exact files counted by the Halstead extractor, checks all 32 stripped files, and runs 15 injected faults. Python import/from lines are removed; Q# open declarations, the namespace wrapper, and @EntryPoint() are removed and the body is dedented. Comparison ignores outer blank lines and trailing whitespace.

Fidelity uses an exact branch simulator without sampling (conditional probabilities at most 1e-12 are omitted), with terminal measurements deferred. References come from analytic algorithm specifications. All eight basis inputs verify the three-qubit QFT with a common global phase. Every branch must have the specified measurement scope; teleportation requires the four resolved Alice outcomes with probability 1/4 each and the correct Bob state for the specified input.

Additional compiler ancillas must return to zero; the Deutsch-Jozsa working ancilla is traced out. Q# has a separate 64-shot runtime check with fixed seeds (7); that finite check does not exhaust every possible runtime path. The CLI fails on incomplete current coverage, a failed circuit, a stripped-file mismatch, or a missed mutation. Historical audit failures are reported separately.

In [1]:
import subprocess, sys
import pandas as pd
pd.set_option("display.width", 200, "display.max_colwidth", 90)
r = subprocess.run([sys.executable, "-X", "utf8", "functional_equivalence.py", "--mutation", "--audit", "471afb3"],
                   capture_output=True, text=True, encoding="utf-8")
summary = [line for line in r.stdout.splitlines() if line and not line.startswith(("[", "caught", "MISSED"))]
print(chr(10).join(summary))
print("exit code:", r.returncode)
if r.returncode:
    raise RuntimeError(r.stderr or "Functional verification failed; see verdicts above")

With_import: 32/32 pass; Without_import: 32/32 match
Mutation test: 15/15 injected faults rejected
Audit of 471afb3: FAIL=19, pass=9, ERROR=3, pass-dist=1
exit code: 0

## Verdicts for the analysed implementations

In [2]:
fe = pd.read_csv("data/functional_equivalence.csv")
fe[["benchmark", "sdk", "status", "fidelity", "leaked", "branches", "measured", "notes"]]

   benchmark        sdk status  ...  branches  measured  notes
0       bell       cirq   pass  ...         1       0 1    NaN
1       bell  pennylane   pass  ...         1       0 1    NaN
2       bell     qiskit   pass  ...         1       0 1    NaN
3       bell     qsharp   pass  ...         1       0 1    NaN
4        GHZ       cirq   pass  ...         1     0 1 2    NaN
5        GHZ  pennylane   pass  ...         1     0 1 2    NaN
6        GHZ     qiskit   pass  ...         1     0 1 2    NaN
7        GHZ     qsharp   pass  ...         1     0 1 2    NaN
8         DJ       cirq   pass  ...         1       0 1    NaN
9         DJ  pennylane   pass  ...         1       0 1    NaN
10        DJ     qiskit   pass  ...         1       0 1    NaN
11        DJ     qsharp   pass  ...         1       0 1    NaN
12  P_ansatz       cirq   pass  ...         1     0 1 2    NaN
13  P_ansatz  pennylane   pass  ...         1     0 1 2    NaN
14  P_ansatz     qiskit   pass  ...         1     0 1 2    NaN
15  P_ansatz     qsharp   pass  ...         1     0 1 2    NaN
16       QFT       cirq   pass  ...         1     0 1 2    NaN
17       QFT  pennylane   pass  ...         1     0 1 2    NaN
18       QFT     qiskit   pass  ...         1     0 1 2    NaN
19       QFT     qsharp   pass  ...         1     0 1 2    NaN
20      qaoa       cirq   pass  ...         1     0 1 2    NaN
21      qaoa  pennylane   pass  ...         1     0 1 2    NaN
22      qaoa     qiskit   pass  ...         1     0 1 2    NaN
23      qaoa     qsharp   pass  ...         1     0 1 2    NaN
24  teleport       cirq   pass  ...         4     0 1 2    NaN
25  teleport  pennylane   pass  ...         4     0 1 2    NaN
26  teleport     qiskit   pass  ...         4     0 1 2    NaN
27  teleport     qsharp   pass  ...         4     0 1 2    NaN
28    Grover       cirq   pass  ...         1     0 1 2    NaN
29    Grover  pennylane   pass  ...         1     0 1 2    NaN
30    Grover     qiskit   pass  ...         1     0 1 2    NaN
31    Grover     qsharp   pass  ...         1     0 1 2    NaN

[32 rows x 8 columns]

In [3]:
wi = pd.read_csv("data/functional_equivalence_without_import.csv")
print(f"Without_import files matching With_import minus preamble: {wi.matches_with_import_minus_preamble.sum()}/{len(wi)}")

Without_import files matching With_import minus preamble: 32/32

## Mutation test of the checker (every injected fault must be rejected)

In [4]:
pd.read_csv("data/functional_equivalence_mutation_test.csv")[["mutated_file", "fault", "status", "caught"]]

                      mutated_file  ... caught
0          Grover/qiskit_grover.py  ...   True
1            Grover/cirq_grover.py  ...   True
2                qaoa/cirq_qaoa.py  ...   True
3              qaoa/qsharp_qaoa.qs  ...   True
4        teleport/cirq_teleport.py  ...   True
5      teleport/qsharp_teleport.qs  ...   True
6   teleport/pennylane_teleport.py  ...   True
7                QFT/qiskit_qft.py  ...   True
8             QFT/pennylane_qft.py  ...   True
9     P_ansatz/pennylane_ansatz.py  ...   True
10                   DJ/cirq_dj.py  ...   True
11               GHZ/qsharp_ghz.qs  ...   True
12             bell/qiskit_bell.py  ...   True
13          bell/pennylane_bell.py  ...   True
14       teleport/cirq_teleport.py  ...   True

[15 rows x 4 columns]

## Audit of the originally submitted implementations (commit `471afb3`)

The implementations in the first public version did not all satisfy the specification
(see the README *Corrections* section). They are re-verified here with the same checker.

In [5]:
au = pd.read_csv("data/functional_equivalence_audit_471afb3.csv")
print(au.status.value_counts().to_string())
au[["benchmark", "sdk", "status", "fidelity", "notes"]]

status
FAIL         19
pass          9
ERROR         3
pass-dist     1

   benchmark  ...                                                                                      notes
0       bell  ...                                                                                        NaN
1       bell  ...                                                                                        NaN
2       bell  ...                                                                                        NaN
3       bell  ...  classical feed-forward after measurement (2 branches): compared output distributions o...
4        GHZ  ...                                                                                        NaN
5        GHZ  ...                                                                                        NaN
6        GHZ  ...                                                                                        NaN
7        GHZ  ...                     QSharpError: Error: Qubit0 released while not in |0⟩ state Call stack:
8         DJ  ...                                                                                        NaN
9         DJ  ...                                                                                        NaN
10        DJ  ...                                                                                        NaN
11        DJ  ...  measurement scope differs from [0, 1] in at least one branch (union: [0, 1, 2]); class...
12  P_ansatz  ...                measurement scope differs from [0, 1, 2] in at least one branch (union: [])
13  P_ansatz  ...             ValueError: expectation-value outputs are not computational-basis measurements
14  P_ansatz  ...                measurement scope differs from [0, 1, 2] in at least one branch (union: [])
15  P_ansatz  ...                measurement scope differs from [0, 1, 2] in at least one branch (union: [])
16       QFT  ...                measurement scope differs from [0, 1, 2] in at least one branch (union: [])
17       QFT  ...                                                        NameError: name 'np' is not defined
18       QFT  ...                measurement scope differs from [0, 1, 2] in at least one branch (union: [])
19       QFT  ...                measurement scope differs from [0, 1, 2] in at least one branch (union: [])
20      qaoa  ...  measurement scope differs from [0, 1, 2] in at least one branch (union: []); fidelity ...
21      qaoa  ...  measurement scope differs from [0, 1, 2] in at least one branch (union: []); fidelity ...
22      qaoa  ...  measurement scope differs from [0, 1, 2] in at least one branch (union: []); fidelity ...
23      qaoa  ...  measurement scope differs from [0, 1, 2] in at least one branch (union: []); fidelity ...
24  teleport  ...            measurement scope differs from [0, 1, 2] in at least one branch (union: [0, 1])
25  teleport  ...            measurement scope differs from [0, 1, 2] in at least one branch (union: [0, 1])
26  teleport  ...            measurement scope differs from [0, 1, 2] in at least one branch (union: [0, 1])
27  teleport  ...            measurement scope differs from [0, 1, 2] in at least one branch (union: [0, 1])
28    Grover  ...  measurement scope differs from [0, 1, 2] in at least one branch (union: []); fidelity ...
29    Grover  ...  measurement scope differs from [0, 1, 2] in at least one branch (union: []); fidelity ...
30    Grover  ...  measurement scope differs from [0, 1, 2] in at least one branch (union: []); fidelity ...
31    Grover  ...                                                                      fidelity 0.140625 < 1

[32 rows x 5 columns]